   length _strfmt_ $7; drop _strfmt_;
   _strfmt_ = ' ';

   array _tlevname_0_{2} $12 _temporary_ ( '           1'
   '           0');

   array _dt_fi_0_{2} _temporary_;

   _node_id_ =  0;
   _new_id_  = -1;
   nextnode_0:
   if _node_id_ eq 0 then do;
         _numval_ = BIN_DEBTINC;
         if missing(_numval_) then do;
            _node_id_ = 1;
            goto nextnode_0;
         end;
         if (_numval_ ge 0.5 and _numval_ lt 10) then do;

            _new_id_ = 1;
         end;
         else if (_numval_ ge 0 and _numval_ lt 0.5) then do;

            _new_id_ = 2;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 2;
         end;
         else if (_numval_ ge 10) then do;
            _new_id_ = 1;
         end;
         else do;
         _new_id_ = 1;
         end;
   end;
   else if _node_id_ eq 1 then do;
         _numval_ = IM_DELINQ;
         if missing(_numval_) then do;
            _node_id_ = 4;
            goto nextnode_0;
         end;
         if (_numval_ ge 1.3 and _numval_ lt 13) then do;

            _new_id_ = 3;
         end;
         else if (_numval_ ge 0 and _numval_ lt 1.3) then do;

            _new_id_ = 4;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 4;
         end;
         else if (_numval_ ge 13) then do;
            _new_id_ = 3;
         end;
         else do;
         _new_id_ = 4;
         end;
   end;
   else if _node_id_ eq 2 then do;
         _numval_ = IM_DELINQ;
         if missing(_numval_) then do;
            _node_id_ = 6;
            goto nextnode_0;
         end;
         if (_numval_ ge 0.65 and _numval_ lt 13) then do;

            _new_id_ = 5;
         end;
         else if (_numval_ ge 0 and _numval_ lt 0.65) then do;

            _new_id_ = 6;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 6;
         end;
         else if (_numval_ ge 13) then do;
            _new_id_ = 5;
         end;
         else do;
         _new_id_ = 6;
         end;
   end;
   else if _node_id_ eq 3 then do;
         _numval_ = BIN_VALUE;
         if missing(_numval_) then do;
            _node_id_ = 7;
            goto nextnode_0;
         end;
         if (_numval_ ge 2.5 and _numval_ lt 10) then do;

            _new_id_ = 7;
         end;
         else if (_numval_ ge 0 and _numval_ lt 2.5) then do;

            _new_id_ = 8;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 8;
         end;
         else if (_numval_ ge 10) then do;
            _new_id_ = 7;
         end;
         else do;
         _new_id_ = 7;
         end;
   end;
   else if _node_id_ eq 4 then do;
         _leaf_id_ = 4;
         _new_id_ = -1;
         _dt_pred_lev_ = 1;
         _dt_pred_prob_ =      0.9303158580267;
         _dt_fi_0_{1} =     0.06968414197329;
         _dt_fi_0_{2} =      0.9303158580267;
   end;
   else if _node_id_ eq 5 then do;
         _leaf_id_ = 5;
         _new_id_ = -1;
         _dt_pred_lev_ = 0;
         _dt_pred_prob_ =     0.81049562682215;
         _dt_fi_0_{1} =     0.81049562682215;
         _dt_fi_0_{2} =     0.18950437317784;
   end;
   else if _node_id_ eq 6 then do;
         _numval_ = IM_DEROG;
         if missing(_numval_) then do;
            _node_id_ = 10;
            goto nextnode_0;
         end;
         if (_numval_ ge 0.5 and _numval_ lt 10) then do;

            _new_id_ = 9;
         end;
         else if (_numval_ ge 0 and _numval_ lt 0.5) then do;

            _new_id_ = 10;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 10;
         end;
         else if (_numval_ ge 10) then do;
            _new_id_ = 9;
         end;
         else do;
         _new_id_ = 10;
         end;
   end;
   else if _node_id_ eq 7 then do;
         _leaf_id_ = 7;
         _new_id_ = -1;
         _dt_pred_lev_ = 1;
         _dt_pred_prob_ =     0.74468085106382;
         _dt_fi_0_{1} =     0.25531914893617;
         _dt_fi_0_{2} =     0.74468085106382;
   end;
   else if _node_id_ eq 8 then do;
         _leaf_id_ = 8;
         _new_id_ = -1;
         _dt_pred_lev_ = 0;
         _dt_pred_prob_ =     0.62068965517241;
         _dt_fi_0_{1} =     0.62068965517241;
         _dt_fi_0_{2} =     0.37931034482758;
   end;
   else if _node_id_ eq 9 then do;
         _leaf_id_ = 9;
         _new_id_ = -1;
         _dt_pred_lev_ = 0;
         _dt_pred_prob_ =     0.77173913043478;
         _dt_fi_0_{1} =     0.77173913043478;
         _dt_fi_0_{2} =     0.22826086956521;
   end;
   else if _node_id_ eq 10 then do;
         _numval_ = IM_CLAGE;
         if missing(_numval_) then do;
            _node_id_ = 12;
            goto nextnode_0;
         end;
         if (_numval_ ge 233.646712188928 and _numval_ lt 1168.23356094464) then do;

            _new_id_ = 11;
         end;
         else if (_numval_ ge 0 and _numval_ lt 233.646712188928) then do;

            _new_id_ = 12;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 12;
         end;
         else if (_numval_ ge 1168.23356094464) then do;
            _new_id_ = 11;
         end;
         else do;
         _new_id_ = 12;
         end;
   end;
   else if _node_id_ eq 11 then do;
         _leaf_id_ = 11;
         _new_id_ = -1;
         _dt_pred_lev_ = 1;
         _dt_pred_prob_ =     0.77272727272727;
         _dt_fi_0_{1} =     0.22727272727272;
         _dt_fi_0_{2} =     0.77272727272727;
   end;
   else if _node_id_ eq 12 then do;
         _numval_ = BIN_VALUE;
         if missing(_numval_) then do;
            _node_id_ = 13;
            goto nextnode_0;
         end;
         if (_numval_ ge 4.5 and _numval_ lt 10) then do;

            _new_id_ = 13;
         end;
         else if (_numval_ ge 0 and _numval_ lt 4.5) then do;

            _new_id_ = 14;
         end;
         else if (_numval_ lt 0) then do;
            _new_id_ = 14;
         end;
         else if (_numval_ ge 10) then do;
            _new_id_ = 13;
         end;
         else do;
         _new_id_ = 13;
         end;
   end;
   else if _node_id_ eq 13 then do;
         _leaf_id_ = 13;
         _new_id_ = -1;
         _dt_pred_lev_ = 1;
         _dt_pred_prob_ =     0.60773480662983;
         _dt_fi_0_{1} =     0.39226519337016;
         _dt_fi_0_{2} =     0.60773480662983;
   end;
   else if _node_id_ eq 14 then do;
         _leaf_id_ = 14;
         _new_id_ = -1;
         _dt_pred_lev_ = 0;
         _dt_pred_prob_ =     0.62777777777777;
         _dt_fi_0_{1} =     0.62777777777777;
         _dt_fi_0_{2} =     0.37222222222222;
   end;
   if _new_id_ >= 0 then do;
       _node_id_ = _new_id_;
      goto nextnode_0;
   end;

   I_BAD = _tlevname_0_{_dt_pred_lev_+1};
   _i_ = 1;
   _dt_predp_ = _dt_fi_0_{_i_};
   P_BAD1 = _dt_predp_;
   _i_+1;
   _dt_predp_ = _dt_fi_0_{_i_};
   P_BAD0 = _dt_predp_;
   _i_+1;
   drop _dt_predp_;
   drop _i_;
   drop _dt_pred_lev_;
   drop _dt_pred_prob_;
   drop _numval_;
   drop _node_id_;
   drop _new_id_;



